FROM quay.io/keycloak/keycloak:26.2.5

# Copia os temas customizados
COPY themes/ /opt/keycloak/themes/

# Opcional: Se precisar de drivers ou extensões extras, faria o build aqui
# RUN /opt/keycloak/bin/kc.sh build
